services:
  scraper:
    build: ./services/scraper
    env_file:
      - .env
    volumes:
      - ./shared/data:/app/shared/data
    restart: "no"

  engine:
    build: ./services/engine
    volumes:
      - ./shared/data:/app/shared/data
    depends_on:
      scraper:
        condition: service_completed_successfully
    restart: "no"

  corners_engine:
    build: ./services/corners_engine
    env_file:
      - .env
    volumes:
      - ./shared/data:/app/shared/data
      - ./shared/mappings:/app/shared/mappings
    depends_on:
      engine:
        condition: service_completed_successfully
    restart: "no"

  api:
    build: ./services/api
    ports:
      - "8880:8880"
    volumes:
      - ./shared/data:/app/shared/data
    depends_on:
      corners_engine:
        condition: service_completed_successfully
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "3330:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      api:
        condition: service_started
    restart: always
